#!/usr/bin/env bash
#a script that displays Best School 10 times, and hi one a new line at the ninth iteration

counter=1

while [ $counter -le 10 ]; do
	if [ "$counter" -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
