#!/usr/bin/env bash
#a script that displays bad luck, good luck, best school

counter=1

while [ "$counter" -le 10 ]; do
	if [ "$counter" -eq 4 ]; then
		echo "bad luck"
	elif [ "$counter" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
