#!/usr/bin/env bash
#script to display hours from 0 to 12

hour=0

while [ "$hour" -le 12 ]; do
	echo "Hour: $hour"

	minute=1

	while [ "$minute" -le 59 ]; do
		printf "%02d:%02d\n" $minute
		((minute++))
	done
	((hour++))
done
