#!/usr/bin/env bash
#a bash script that give information about the "school" file

file_path="school"

if [ -e "$file_path" ]; then
	echo "school file exists"

	if [ -r "$file_path" ]; then
		if [ -s "$file_path" ]; then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		
		if [ -f "$file_path" ]; then
			echo "school is a regular file"
		fi
	fi
else
	echo "school file does not exist"
fi
